perfect_cms/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');
Router::extensions(['pdf']);

Router::scope('/', function ($routes) {
    $routes->extensions(['json', 'pdf']);
    $routes->resources('Incidents');
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Dashboard', 'action' =>'index']);
    //$routes->connect('/', ['controller' => 'Incidents', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

perfect_cms/src/Model/Table/AssistanceTypesTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\AssistanceType;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * AssistanceTypes Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Agencies
 * @property \Cake\ORM\Association\BelongsToMany $IncidentTypes
 */
class AssistanceTypesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('assistance_types');
        $this->displayField('name');
        $this->primaryKey('id');

        $this->belongsTo('Agencies', [
            'foreignKey' => 'agency_id'
        ]);
        $this->belongsToMany('IncidentTypes', [
            'foreignKey' => 'assistance_type_id',
            'targetForeignKey' => 'incident_type_id',
            'joinTable' => 'incident_types_assistance_types'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->add('id', 'valid', ['rule' => 'numeric'])
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('name', 'create')
            ->notEmpty('name');

        $validator
            ->allowEmpty('number');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['agency_id'], 'Agencies'));
        return $rules;
    }
}

perfect_cms/src/Controller/AssistanceTypesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Incidents Controller
 *
 * @property \App\Model\Table\IncidentsTable $Incidents
 */
class AssistanceTypesController extends AppController
{

    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $assistanceTypes = $this->AssistanceTypes->find('all')->contain(['Agencies']);
        $this->set('assistanceTypes', $assistanceTypes);
    }

    /**
     * View method
     *
     * @param string|null $id Incident id.
     * @return void
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function view($id = null)
    {
        $assistanceType = $this->AssistanceTypes->get($id, [
            'contain' => ['Agencies']
        ]);
        $this->set('assistanceType', $assistanceType);
        $this->set('_serialize', ['assistanceType']);
    }


    /**
     * Add method
     *
     * @return void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $assistanceType = $this->AssistanceTypes->newEntity();

        if ($this->request->is('post')) {
            $assistanceType = $this->AssistanceTypes->patchEntity($assistanceType, $this->request->data);
            $this->log($assistanceType);
            
            
        
            if ($this->AssistanceTypes->save($assistanceType)) {
                $this->Flash->success(__('The Assistance Type has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The Assistance Type could not be saved. Please, try again.'));
            }
        }

        $agencies = $this->AssistanceTypes->Agencies->find('list', ['limit' => 200]);
        $this->set(compact('assistanceType', 'agencies'));
        $this->set('_serialize', ['assistanceType']);


    }

    /**
     * Edit method
     *
     * @param string|null $id Incident id.
     * @return void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $assistanceType = $this->AssistanceTypes->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $assistanceType = $this->AssistanceTypes->patchEntity($assistanceType, $this->request->data);
            
            if ($this->AssistanceTypes->save($assistanceType)) {
                $this->Flash->success(__('The Assistance Type has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The Assistance Type could not be saved. Please, try again.'));
            }
        }
 

        $agencies = $this->AssistanceTypes->Agencies->find('list', ['limit' => 200]);
        $this->set(compact('assistanceType', 'agencies'));
        $this->set('_serialize', ['assistanceType']);
        $this->render('add');
    }

    /**
     * Delete method
     *
     * @param string|null $id Incident id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $assistanceType = $this->AssistanceTypes->get($id);
        if ($this->AssistanceTypes->delete($assistanceType)) {
            $this->Flash->success(__('The assistance type has been deleted.'));
        } else {
            $this->Flash->error(__('The assistance type could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}

perfect_cms/src/Template/AssistanceTypes/add.ctp
<?= $this->element('content-header', ['title' => 'Create New Assistance Type']);
    $this->fetch('content-header'); ?>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">Create New Assistance Type</h3>
                </div>
                
                <?= $this->Form->create($assistanceType, ['class' => 'form-horizontal', 'id'=>'addForm']) ?>
                <!-- <form class="form-horizontal">-->
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name" class="col-sm-4 control-label">Assistance Type : </label>
                            <div class="col-sm-4">
                                <?= $this->Form->text('name', ['class' => 'form-control', 'placeholder' => 'Enter the type of assistance this category will provide']) ?>
                                <!-- input type="email" class="form-control" id="name" placeholder="e.g. Sally" -->
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="number" class="col-sm-4 control-label">Assistance Hotline : </label>
                            <div class="col-sm-4">
                                <?= $this->Form->input('number', ['label'=>false, 'class' => 'form-control', 'placeholder' => 'Enter the contact hotline for this assistance']) ?>
                                <!-- input type="email" class="form-control" id="name" placeholder="e.g. Sally" -->
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="agency" class="col-sm-4 control-label">Agency</label>
                            <div class="col-sm-4">
                                <?= $this->Form->input('agency_id', [ 'label' => false, 'class' => 'form-control', 'options' => $agencies]); ?>
                            </div>
                        </div>
                        
                
                    </div>
                    
                    <div class="box-footer">
                        <?= $this->Form->button('Reset', ['type' => 'reset', 'class' => 'btn btn-default']) ?>
                        <!-- button type="submit" class="btn btn-default">Reset</button -->
                        <?= $this->Form->button('Submit', ['type' => 'submit', 'class' => 'btn btn-success pull-right']) ?>
                        <!-- button type="submit" class="btn btn-success pull-right">Submit</button -->
                    </div>
                <?= $this->Form->end() ?>
                <!-- /form -->
            </div>
        </div>
            
        <div class="clearfix visible-sm-block"></div>
    </div>
</section>

<script>

$.validator.addMethod(
    "regex",
    function(value, element, regexp) {
        var check = false;
        return this.optional(element) || regexp.test(value);
    },
    "This field consists of invalid characters."
);

$( "#addForm" ).validate({
          rules: {
            name: {
				required: true,
				regex: /^[a-zA-Z][a-zA-Z\d\-_\s]+$/
            },
			number:{
				required: true,
				digits: true
			}
          }
        });
</script>

perfect_cms/src/Template/AssistanceTypes/edit.ctp
<?= $this->element('content-header', ['title' => 'Update Assistance Type']);
    $this->fetch('content-header'); ?>

<section class="content">
    <div class="row">
        <div class="col-md-8">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">Update Assistance Type</h3>
                </div>
                <?= $this->Form->create($assistanceType, ['class' => 'form-horizontal']) ?>
                <!-- form class="form-horizontal" -->
                    <div class="box-body">
                            <div class="form-group">
                            <label for="assistanceName" class="col-sm-4 control-label"> Name</label>
                            <div class="col-sm-6">
                                <?= $this->Form->input('name', [ 'label' => false, 
                                                                'class' => 'form-control', 
                                                                'placeholder' => 'e.g. Dengue Extermination' ]); ?>
                            </div>
                        </div>
                    <div class="form-group">
                            <label for="agency" class="col-sm-4 control-label">Agency</label>
                            <div class="col-sm-4">
                                <?= $this->Form->input('agency_id', [ 'label' => false, 
                                                                            'class' => 'form-control', 
                                                                            'options' => $agencies]); ?>
                            </div>
                    </div>

                       
                        
                        
                            
               
                        
                    </div>
                    
                    
                    
                    <div class="box-footer">
                        <?= $this->Form->button('Reset', ['type' => 'reset', 'class' => 'btn btn-default']) ?>
                        <!-- button type="submit" class="btn btn-default">Reset</button -->
                        <?= $this->Form->button('Update', ['type' => 'submit', 'class' => 'btn btn-success pull-right']) ?>
                    </div>
                <?= $this->Form->end() ?>
            </div>
        </div>
            
        <div class="clearfix visible-sm-block"></div>
    </div>
</section>

<!-- 
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $incident->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $incident->id)]
            )
        ?></li>
        <li><?= $this->Html->link(__('List Incidents'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Incident Types'), ['controller' => 'IncidentTypes', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Incident Type'), ['controller' => 'IncidentTypes', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Call Operators'), ['controller' => 'CallOperators', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Call Operator'), ['controller' => 'CallOperators', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="incidents form large-9 medium-8 columns content">
    <?= $this->Form->create($incident) ?>
    <fieldset>
        <legend><?= __('Edit Incident') ?></legend>
        <?php
            echo $this->Form->input('location');
            echo $this->Form->input('description');
            echo $this->Form->input('status');
            echo $this->Form->input('reporter_name');
            echo $this->Form->input('reporter_mobile');
            echo $this->Form->input('datetime');
            echo $this->Form->input('incident_type_id', ['options' => $incidentTypes]);
            echo $this->Form->input('call_operator_id', ['options' => $callOperators]);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>
-->

perfect_cms/src/Template/AssistanceTypes/index.ctp
<?= $this->element('content-header', ['title' => 'List of Assistance Type Records']);
    $this->fetch('content-header'); ?>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <!-- /.box -->
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Type</th>     
                                <th>Agency</th>
                                <th>Assistance Hotline</th>                     
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        <!-- if there are no assistance type, i will print a message -->
                        <?php if ( empty($assistanceTypes) ) :
                                echo "There are no assistance type records.";
                              else :
                                foreach ($assistanceTypes as $assistanceType) : ?>
                                <tr>
                                    <td><?= $assistanceType->name ?></td>
                                    <td><?= $assistanceType->has('agency') ? $assistanceType->agency->name : '' ?>
                                    </td>
                                    <td><?= $assistanceType->number ?></td>
                                    <td>
                                        <?= $this->Form->button('Update', [ 'type' => 'submit', 
                                                                            'class' => 'btn btn-warning', 
                                                                            'onclick' => 'window.location.href=\''. $this->Url->build(['action' => 'edit', $assistanceType->id ]) .'\';']) ?>
                                        <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $assistanceType->id], ['class'=>'btn btn-danger', 'confirm' => __('Are you sure you want to delete # {0}?', $assistanceType->id)]) ?>
                                    </td>
                                </tr>
                        <?php   endforeach;
                              endif; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
    <script>
        $(function () {
          $("#example1").DataTable();
          $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false
          });
        });
    </script>
</section>

perfect_cms/src/Template/AssistanceTypes/view.ctp
<!--<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('Edit Incident'), ['action' => 'edit', $incident->id]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete Incident'), ['action' => 'delete', $incident->id], ['confirm' => __('Are you sure you want to delete # {0}?', $incident->id)]) ?> </li>
        <li><?= $this->Html->link(__('List Incidents'), ['action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Incident'), ['action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Incident Types'), ['controller' => 'IncidentTypes', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Incident Type'), ['controller' => 'IncidentTypes', 'action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Call Operators'), ['controller' => 'CallOperators', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Call Operator'), ['controller' => 'CallOperators', 'action' => 'add']) ?> </li>
    </ul>
</nav>
-->


<div class="assistance view large-9 medium-8 columns content">
    <h3><?= h($assistanceType->id) ?></h3>
    <table class="vertical-table">
        <tr>
            <th><?= __('Assistance Type') ?></th>
            <td><?= h($assistanceType->name) ?></td>
        </tr>
       
     
        <tr>
            <th><?= __('Agency') ?></th>
            <td><?= $assistanceType->has('agency') ? $this->Html->link($assistanceType->agency->name, ['controller' => 'Agencies', 'action' => 'view', $assistanceType->agency->id]) : '' ?></td>
        </tr>
       
    </table>

    
</div>